# Declare project language.
# @link https://about.travis-ci.org/docs/user/languages/php/
language: php

php:
  - 7.0
  - 7.1

# Use this to prepare the system to install prerequisites or dependencies.
# e.g. sudo apt-get update.
# Failures in this section will result in build status 'errored'.
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - git clone -q --depth=1 https://github.com/techpivot/phalcon-ci-installer.git
  - bash ./phalcon-ci-installer/bin/install-phalcon.sh

install:
  - composer self-update
  - composer --prefer-source install

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
# before_script:

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
  - vendor/bin/phpcs ./Library/

# The cache’s purpose is to make installing language-specific dependencies easy and fast,
# so everything related to tools like Bundler, pip, Composer, npm, Gradle, Maven, is what should go into the cache.
cache:
  directories:
    - vendor

# Receive notifications for build results.
# @link https://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
    email: false