# Declare project language.
# @link https://about.travis-ci.org/docs/user/languages/php/
language: php

php:
  - 7.1

# The cache’s purpose is to make installing language-specific dependencies easy and fast,
# so everything related to tools like Bundler, pip, Composer, npm, Gradle, Maven, is what should go into the cache.
cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/pear
    - $HOME/cphalcon
    - $HOME/ext

env:
  global:
    - ZEND_DONT_UNLOAD_MODULES=1
    - CC="ccache gcc"
    - PATH="$PATH:~/bin"
    - PHALCON_VERSION="v3.2.1"
    - ES_VERSION=5.5.1 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz

before_install:
  - sudo apt-get -qq update
  - export PHP_MAJOR="$(echo $TRAVIS_PHP_VERSION | cut -d '.' -f 1)"
  - export PHP_EXTENSION_DIR=$(php-config --extension-dir)
  - if [ ! -z "${GH_TOKEN}" ]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;
  - if [ ! -f "$HOME/cphalcon/$PHALCON_VERSION/tests/_ci/phalcon.ini" ]; then mkdir -p $HOME/cphalcon/$PHALCON_VERSION && git clone -q --depth=1 https://github.com/phalcon/cphalcon.git $HOME/cphalcon/$PHALCON_VERSION >/dev/null 2>&1; fi;

install:
  - travis_retry composer install --prefer-dist --no-interaction --quiet --no-ansi --no-progress --optimize-autoloader --dev --no-suggest --ignore-platform-reqs
  - if [ ! -f $HOME/ext/$PHP_VERSION/$PHALCON_VERSION/phalcon.so ]; then cd $HOME/cphalcon/$PHALCON_VERSION/build && bash ./install --phpize $(phpenv which phpize) --php-config $(phpenv which php-config) && mkdir -p $HOME/ext/$PHP_VERSION/$PHALCON_VERSION && cp $PHP_EXTENSION_DIR/phalcon.so $HOME/ext/$PHP_VERSION/$PHALCON_VERSION/phalcon.so; fi;
  - if [ -f $HOME/ext/$PHP_VERSION/$PHALCON_VERSION/phalcon.so ]; then cp $HOME/ext/$PHP_VERSION/$PHALCON_VERSION/phalcon.so $PHP_EXTENSION_DIR/phalcon.so; fi;
  - phpenv config-add $HOME/cphalcon/$PHALCON_VERSION/tests/_ci/phalcon.ini
  - cd $TRAVIS_BUILD_DIR
  - $(phpenv which php) --ri phalcon
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - 'echo "script.disable_dynamic: false" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - sleep 20

before_script:
    - ./bin/elasticsearch/initialize.sh http://127.0.0.1:9200
    - for f in $(grep -rl '192.168.100.100' Tests/Library/); do sed -i 's/192.168.100.100/127.0.0.1/' $f; done
    - curl http://127.0.0.1:9200


script:
  - vendor/bin/phpcs --standard=./ruleset.xml ./Library/
  - vendor/bin/phpcs --standard=./ruleset.xml ./Tests/
  - vendor/phpunit/phpunit/phpunit -c Tests/phpunit.xml

notifications:
    email: false
